[versions]
log4j = "2.26.1"
guava = "33.7.1-jre"
spotbugs-annotations = "4.10.4"
# test libs
junit = "6.1.3"
truth = "1.4.5"
mockito = "5.23.0"
# langs
kotlin = "2.4.10"
# plugins
spotless = "8.10.2"
checkstyle = "10.12.0"
spotbugs-plugin = "6.5.11"
buildtimetracker = "5.0.2"
testsets = "4.1.0"

[libraries]
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-slf4j2 = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
# test libs
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
buildtimetracker = { id = "com.asarkar.gradle.build-time-tracker", version.ref = "buildtimetracker" }
testsets = { id = "org.unbroken-dome.test-sets", version.ref = "testsets" }
