name: dependency-submission
run-name: dependency-submission by @${{ github.actor }}

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  dependency-submission:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-java-gradle

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6
        with:
          dependency-graph: 'generate-and-submit'
