name: dependency-submission
run-name: dependency-submission by @${{ github.actor }}

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-java-gradle

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph: 'generate-and-submit'
